# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='id',
        ),
        migrations.AlterField(
            model_name='channel',
            name='categories',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='root_of', serialize=False, to='channels.Category'),
        ),
    ]
