# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20171105_1150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryTree',
        ),
    ]
