# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_auto_20171109_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={},
        ),
    ]
