# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together=set([('name', 'parent')]),
        ),
    ]
