# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20171114_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='path',
            field=models.TextField(null=True),
        ),
    ]
