# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20171104_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='categories',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='root_of', to='channels.Category'),
        ),
    ]
