# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channel_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
