# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 18:07
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_auto_20171106_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='categories',
            field=mptt.fields.TreeOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='root_of', to='channels.CategoryTree'),
        ),
    ]
